### ISSUE TITLE
Líneas de referencia y ejemplo

### ISSUE THREAD

**Issue by PabloGGaray** [aloctavodia/Modelado_Bayesiano#7]
https://github.com/Grupo-de-modelado-probabilista/Modelado_Bayesiano/blob/9b3c1d6bbe05f075195aba8e90c7caae91b85031/01_Inferencia_Bayesiana.ipynb?short_path=dda8a4e#L454

En está subsección dice "El cálculo del a posteriori ocurre en las lineas 18, 22 y 26", pero al parecer las líneas del código que le siguen al texto cambiaron ¿es solo la línea 20 la que hay que indicar en el texto?.

Después en el ejercicio 3.

https://github.com/Grupo-de-modelado-probabilista/Modelado_Bayesiano/blob/9b3c1d6bbe05f075195aba8e90c7caae91b85031/01_Inferencia_Bayesiana.ipynb?short_path=dda8a4e#L822

No está especificado cual es el ejemplo del diagnóstico.

Esos cambios los puedo subir junto algunos typos.

**Comment by aloctavodia** [comment]
1) Si, solo la linea 20
2) Borré ese ejemplo, borrá el ejercicio

Fijate de hacer los cambios sobre la última versión, hace unos minuto la cambié.
